branches:
  only:
    - master

language: ruby
rvm:
  - "2.1.0"
  - "2.1.2"
  - "2.1.5"
  - "2.2.0"
  - "2.2.1"
  - "2.2.2"
  - "2.2.3"
  # Add jruby when issue #3371 is fixed https://github.com/jruby/jruby/issues/3371
  # - "jruby-9.0.1.0"

install: 
  - bundle install
    # Assure order of files for qed
  - touch demo/fordir/subdir/1
  - chmod 444 demo/forfile/readable
script: 
  - bundle exec rspec spec
  - bundle exec qed demo

