branches:
  only:
    - master

language: ruby
rvm:
  - "2.3.1"
  - "2.4.0"

install: 
  - bundle install
    # Assure order of files for qed
  - touch demo/fordir/subdir/1
  - chmod 444 demo/forfile/readable
script: 
  - bundle exec rspec spec
  - bundle exec qed demo
  - CODECLIMATE_REPO_TOKEN=${CODECLIMATE_LAB42CORE_TOKEN} bundle exec codeclimate-test-reporter

