branches:
  only:
    - master

language: ruby
rvm:
  - "2.0.0"
  - "2.1.2"
  - "2.1.5"
  - "2.2.0"
  - "2.2.1"

install: 
  - bundle install
    # Assure order of files for qed
  - touch demo/fordir/subdir/1
  - chmod 444 demo/forfile/readable
script: 
  - bundle exec rspec spec
  - bundle exec qed demo

