require_relative './core/array'
require_relative './core/dir'
require_relative './core/enumerable'
# require_relative './core/hash'
# require_relative './core/kernel'
# require_relative './core/object'
# require_relative './core/module'
# require_relative './core/open_object'
# require_relative './core/behavior_args'
# require_relative './core/behavior'
